### ISSUE TITLE
Degrade axes based on number of blocks broken

### ISSUE THREAD

**Issue by aph3rson** [Cristichi/CrisTreeCapitator#3]
Older plugins will degrade the user's axe based on the number of logs broken. This makes the tool much more balanced.

This would be better overall, perhaps as a server-configurable option.

**Comment by Mihoshika** [comment]
I second this. If you need an example of how to do this, it is shown [here](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/skills/woodcutting/WoodcuttingManager.java#L199) on McMMO's github, which runs on 1.15.2
