### ISSUE TITLE
Netherite axes recieve more damage than they should

### ISSUE THREAD

**Issue by CCF100** [Cristichi/CrisTreeCapitator#5]
It may just be me, but it seems to me like the amount of damage that this plugin takes off of Netherite Axes is way too much... My axes break after I chop down like 20 oak trees...

**Comment by Cristichi** [comment]
Thank you so much, I was wondering why was it happening and then I realised it's counting leaves as blocks destroyed by the axe, which means each leaf is damaging the axe as well, which is not the way I want it to work. A fix is coming! Also, expect more configurable options on that, like if the axe should not be broken.
